services:
  - type: web
    name: mutxri-backend
    runtime: python
    plan: free
    repo: https://github.com/mutxri/MUTXRI-TERMINAL
    branch: backend
    healthCheckPath: /api/health
    buildCommand: pip install -r requirements.txt
    startCommand: python afri_server.py
    envVars:
      - key: MONGODB_URI
        sync: false
